export const vistServiceHistoryDetails = {
    getVisitServiceHistoryListSuccess: 'getVisitServiceHistoryListSuccess/visitHistory',
    getVisitServiceHistoryDetailsSuccess: 'getVisitServiceHistoryDetailsSuccess/visitHistory',
    getVisitServiceHistoryByIdDetailSuccess: 'getVisitServiceHistoryByIdDetailSuccess/visitHistory',
    updateVisitHistoryFilter: 'updateVisitHistoryFilter/visitHistory',
    getServiceCategorySuccess: "getServiceCategorySuccess/VisitHistory",
    getSubmittedResponse: "getSubmittedResponse/visitHistory",
    getAllServiceProviders: "getServiceProviders/visitHistory",
    getServiceRequestId: 'getServiceRequestId/visitHistory',
    getServiceTypeSuccess: 'get_type_success/visitHistory',
    clearServiceTypes: 'clearServiceTypes/visitHistory',
    clearServiceProviders: 'clearServiceProviders/visitHistory',
    getHistoryListCountSuccess: 'getHistoryListCountSuccess/visitHistory',
    getVisitFeedBack: 'getVisitFeedBack/visit',
    getAllPatientForServiceProviders: "getAllPatientForServiceProviders/visitHistory",
    clearPatientForServiceProviders: "clearPatientForServiceProviders/visitHistory",
    formDirty: 'formDirty/visitHistory',
    visitHistoryLoading: 'visitHistoryLoading/visitHistory',
    getAssessmentQuestionsListSuccess: 'getAssessmentQuestionsListSuccess/visitHistory'
};