export const PatientProfile = {
    getProfilePercentageSuccess: 'get_profile_percentage_success/PatientProfile',
    setPatient: 'setPatient/PatientProfile',
    getPersonalDetailSuccess: 'getPersonalDetailSuccess/PatientProfile',
    getImgSuccess: 'getImgSuccess/PatientProfile',
    getPointServiceSuccess: 'getPointServiceSuccess/PatientProfile',
    getManageConnectionSuccess: 'getManageConnectionSuccess/PatientProfile',
    getSelectedLanguageDetails: 'getSelectedLanguageDetails/PatientProfile',
    getSelectedClinicalConditionDetails: 'getSelectedClinicalConditionDetails/PatientProfile',
    clearState: 'clearState/PatientProfile',
    setESP: 'setESP/PatientProfile',
    get_esp_personal_detail_success:'get_esp_personal_detail_success/PatientProfile',
    upload_esp_img_success:'upload_esp_img_success/PatientProfile',
    getESPEducationSuccess:'getESPEducationSuccess/PatientProfile',
    setParticipantProfile: 'setParticipantProfile/PatientProfile',
    getPatientVitalsSuccess: 'getPatientVitalsSuccess/PatientProfile',
    getEmergencyContactDetailsSuccess: 'getEmergencyContactDetailsSuccess/PatientProfile',
    getAttorneyContactDetailsSuccess: 'getAttorneyContactDetailsSuccess/PatientProfile',
    getPatientCoreoDetailsSuccess: 'get_Patient_CoreoDetails_Success/coreoInformation',
    getPatientRiskScoreSuccess: 'get_Patient_RiskScore_Success/coreoInformation'
};