export const VisitServiceDetails = {
    getVisitServiceDetailsSuccess: 'get_visit_service_details_success/visitservicedetails',
    getVisitServiceScheduleSuccess: 'get_visit_service_schedule_success/visitservicedetails',
    getServiceRequestId: 'get_service_requestId/visitservicedetails',
    updateHireServiceRequestByServiceProvider: 'updateHireServiceRequestByServiceProvider/visitservicedetails',
    getVisitServiceEligibityStatusSuccess: 'getVisitServiceEligibityStatusSuccess/visitservicedetails',
    getDaysSuccess: 'getDaysSuccess/visitservicedetails',
    updateServiceRequestByServiceProviderSuccess: 'updateServiceRequestByServiceProviderSuccess/visitservicedetails',
    setEntityServiceProviderSuccess: 'getDaysSuccess/setEntityServiceProvider',
    canInitiateConversationSuccess:'canInitiateConversationSuccess/visitservicedetails',
    formDirtyVisitServiceDetails: 'formDirtyVisitServiceDetails/visitservicedetails',
    isScheduleLoading: 'isScheduleLoading/visitservicedetails',
    cancelHiredRequest: 'cancelHiredRequest/visitservicedetails',

    //New Integration
    getServiceRequestListSuccess: 'getServiceRequestListSuccess/visitservicedetails',
    getSchedulesListSuccess: 'getSchedulesListSuccess/visitservicedetails',
    getVisitListSuccess: 'getVisitListSuccess/visitservicedetails',
    getVisitListCountSuccess: 'getVisitListCountSuccess/visitservicedetails',
    getVisitStatusSuccess: 'getVisitStatusSuccess/visitservicedetails',
    getServiceVisitDetailsSuccess: 'getServiceVisitDetailsSuccess/visitservicedetails',
    startLoading: 'startLoading/visitservicedetails',
    endLoading: 'endLoading/visitservicedetails',
    disableShowmore: 'disableShowmore/visitservicedetails',
    clearESPList: 'clearESPList/visitservicedetails',
    getEntityServiceProviderListSuccess: 'getEntityServiceProviderListSuccess/visitservicedetails',
    setActiveTab: 'setActiveTab/visitservicedetails',
    getfirstlastvisitdateSuccess: 'getfirstlastvisitdateSuccess/visitservicedetails',
    saveScheduleType: 'saveScheduleType/visitservicedetails',
    setAddNewScheduledClicked: 'setAddNewScheduledClicked/visitservicedetails',
    resetState:"visitServiceDetails/resetState",
    setVisitDate: 'setVisitDate/visitservicedetails',
    setEntityDashboard: 'setEntityDashboard/visitservicedetails',
    loadingESPList: 'loadingESPList/visitservicedetails',
    getPaymentAvailabilitySuccess: 'getPaymentAvailabilitySuccess/visitservicedetails',
    setServicePlanVisitId: 'setServicePlanVisitId/visitServiceDetails',
    setActivePage: 'setActivePage/visitServiceDetails',
    setPlanScheduleId: 'setPlanScheduleId/visitservicedetails'
  }