export const Schedule = {
    getServiceCategorySuccess: 'getServiceCategorySuccess/schedule',
    getServiceTypeSuccess: 'getServiceTypeSuccess/schedule',
    getPatientAddressSuccess: 'getPatientAddressSuccess/schedule',
    getStateSuccess: 'getStateSuccess/schedule',
    setSelectedPos: 'setSelectedPos/schedule',
    getValidPatientAddressSuccess: 'getValidPatientAddressSuccess/schedule',
    getEntityServiceProviderListSuccess: 'getEntityServiceProviderListSuccess/schedule',
    getRecurringPatternSuccess: 'getRecurringPatternSuccess/schedule',
    getDaysSuccess: 'getDaysSuccess/Schedule',
    disableShowmore: 'disableShowmore/Schedule',
    clearESPList: 'clearESPList/Schedule',
    createOrEditAssessmentSuccess:'schedule/assessmentCreateOrEditSuccess',
    getAssessmentDetailSuccess: 'Schedule/getAssessmentDetailSuccess',
};