export const VisitServiceRequestList = {
    getServiceRequestCountListSuccess: 'get_service_request_countList_success/visitservicerequest',
    getServiceRequestTableListSuccess: 'get_service_request_tableList_success/visitservicerequest',
    getServiceRequestStatusSuccess: 'get_servicerequest_status_success/visitservice',
    clearRequestStatus: 'clear_request_status/visitservice',
    getScheduleTypeSuccess: 'get_schedule_type_success/visitservice',
    clearScheduleType: 'clear_schedule_type/visitservice',
    getServiceRequestDetailsSuccess: 'get_service_request_details/visitservicerequest',
    getServiceRequestApprovalStatus: 'get_approval_status/visitservicerequest',
    getDiagnosisCodeSuccess: 'getDiagnosisCodeSuccess/visitservicerequest',
    setPaginationRowCountSuccess: 'set_pagination_row_count_success/visitservicerequest',
    setActiveSubTab: 'setActiveSubTab/visitservicerequest',
    checkServiceType: 'checkServiceType/visitservicerequest',
    setServiceType: 'setServiceType/visitservicerequest',
    setFilterApplied: 'setFilterApplied/visitservicerequest',
    setServiceRequestStatus: 'setServiceRequestStatus/visitservicerequest',
    resetFilter: 'resetFilter/visitservicerequest',
    setScheduleType: 'setScheduleType/visitservicerequest',
    setImpersinated: 'setImpersinated/visitservicerequest',
    setServiceCategory: 'setServiceCategory/visitservicerequest'
  }